#!/bin/sh

#    --initialize-at-run-time=org.postgresql.sspi.SSPIClient
#    --initialize-at-run-time=java.lang.Math\$RandomNumberGeneratorHolder \
#    -J-Dclojure.compiler.direct-linking=true \
#    -J-Dclojure.spec.skip-macros=true \
#    -J-Xmx4G \
#    -H:+JNI 
native-image \
    --enable-url-protocols=file,https,http \
    --report-unsupported-elements-at-runtime \
    --no-fallback \
    --no-server \
    --enable-all-security-services \
    --initialize-at-build-time \
    --verbose \
    --static \
    -H:+ReportExceptionStackTraces \
    -H:Name="onecli" \
    -jar target/uberjar/onecli-0.6.0-SNAPSHOT-standalone.jar
