#!/bin/sh
lein uberjar
mkdir -p test-data/repo
set -x
cd test-data/repo
rm -f *.ds*
java -jar ../../target/uberjar/degasolv-1.0.2-SNAPSHOT-standalone.jar generate-card -i "b" -v "2.3.0" -l "https://example.com/repo/b-2.3.0.zip" -r "d" -r "c>=3.5.0" -o $PWD/b-2.3.0.zip.dscard
java -jar ../../target/uberjar/degasolv-1.0.2-SNAPSHOT-standalone.jar generate-card -i "c" -v "2.4.7" -l "https://example.com/repo/c-2.4.7.zip" -o $PWD/c-2.4.7.zip.dscard
java -jar ../../target/uberjar/degasolv-1.0.2-SNAPSHOT-standalone.jar generate-card -i "c" -v "3.5.0" -l "https://example.com/repo/c-3.5.0.zip" -r "e>=1.8.0" -o $PWD/c-3.5.0.zip.dscard
java -jar ../../target/uberjar/degasolv-1.0.2-SNAPSHOT-standalone.jar generate-card -i "d" -v "0.8.0" -l "https://example.com/repo/d-0.8.0.zip" -r "e>=1.1.0,<2.0.0" -o $PWD/d-0.8.0.zip.dscard
java -jar ../../target/uberjar/degasolv-1.0.2-SNAPSHOT-standalone.jar generate-card -i "e" -v "1.8.0" -l "https://example.com/repo/e-1.8.0.zip" -o $PWD/e-1.8.0.zip.dscard
java -jar ../../target/uberjar/degasolv-1.0.2-SNAPSHOT-standalone.jar generate-card -i "e" -v "2.1.0" -l "https://example.com/repo/e-2.1.0.zip" -o $PWD/e-2.1.0.zip.dscard
java -jar ../../target/uberjar/degasolv-1.0.2-SNAPSHOT-standalone.jar generate-card -i "e" -v "2.4.0" -l "https://example.com/repo/e-2.4.0.zip" -o $PWD/e-2.4.0.zip.dscard
java -jar ../../target/uberjar/degasolv-1.0.2-SNAPSHOT-standalone.jar generate-repo-index -d $PWD -o $PWD/index.dsrepo
