#!/bin/sh
lein uberjar
set -ex

rm -rf test-data/repo
mkdir -p test-data/repo

cd test-data/repo
java -jar ../../target/uberjar/degasolv-1.0.2-SNAPSHOT-standalone.jar generate-card -i "b" -v "2.3.0" -l "https://example.com/repo/b-2.3.0.zip" -r "d" -r "c>=3.5.0" -o $PWD/b-2.3.0.zip.dscard


java -jar ../../target/uberjar/degasolv-1.0.2-SNAPSHOT-standalone.jar generate-card -i "c" -v "2.4.7" -l "https://example.com/repo/c-2.4.7.zip" -o $PWD/c-2.4.7.zip.dscard

java -jar ../../target/uberjar/degasolv-1.0.2-SNAPSHOT-standalone.jar generate-card -i "d" -v "0.8.0" -l "https://example.com/repo/d-0.8.0.zip" -r "e>=1.1.0,<2.0.0" -o $PWD/d-0.8.0.zip.dscard
java -jar ../../target/uberjar/degasolv-1.0.2-SNAPSHOT-standalone.jar generate-card -i "e" -v "2.1.0" -l "https://example.com/repo/e-2.1.0.zip" -o $PWD/e-2.1.0.zip.dscard
java -jar ../../target/uberjar/degasolv-1.0.2-SNAPSHOT-standalone.jar generate-card -i "e" -v "2.4.0" -l "https://example.com/repo/e-2.4.0.zip" -o $PWD/e-2.4.0.zip.dscard
java -jar ../../target/uberjar/degasolv-1.0.2-SNAPSHOT-standalone.jar generate-repo-index -d $PWD -o $PWD/index.dsrepo
echo "These should fail"
if java -jar ../../target/uberjar/degasolv-1.0.2-SNAPSHOT-standalone.jar generate-card -i "b" -l "https://example.com/repo/b-2.3.0.zip" -r "d" -r "c>=3.5.0" -o $PWD/b-2.3.0.zip.dscard
then
    exit 1
fi
if java -jar ../../target/uberjar/degasolv-1.0.2-SNAPSHOT-standalone.jar generate-card -v "2.3.0" -l "https://example.com/repo/b-2.3.0.zip" -r "d" -r "c>=3.5.0" -o $PWD/b-2.3.0.zip.dscard
then
    exit 1
fi
if java -jar ../../target/uberjar/degasolv-1.0.2-SNAPSHOT-standalone.jar generate-card -i "b" -v "2.3.0" -r "d" -r "c>=3.5.0" -o $PWD/b-2.3.0.zip.dscard
then
    exit 1
fi
if java -jar ../../target/uberjar/degasolv-1.0.2-SNAPSHOT-standalone.jar resolve-locations "b"
then
    exit 1
fi
if java -jar ../../target/uberjar/degasolv-1.0.2-SNAPSHOT-standalone.jar query-repo -r $PWD/index.dsrepo --query "e>2.0.0|c<4.0.0"
then
    exit 1
fi

echo '#degasolv.resolver/PackageInfo {:id "c", :version "3.5.0", :location "https://example.com/repo/c-3.5.0.zip", :requirements [#degasolv.resolver/Requirement {:status :present, :id "e", :spec [[#degasolv.resolver/VersionPredicate {:relation :greater-equal, :version "1.8.0"}]]}]]}' > $PWD/c-3.5.0.zip.dscard
if java -jar ../../target/uberjar/degasolv-1.0.2-SNAPSHOT-standalone.jar generate-repo-index -d $PWD -o $PWD/index.dsrepo
then
    exit 1
fi
echo '#degasolv.resolver/PackageInfo {:id "c", :version "3.5.0", :location "https://example.com/repo/c-3.5.0.zip", :requirements [#degasolv.resolver/Requirement {:status :present, :id "e", :spec [[#degasolv.resolver/VersionPredicate {:relation :greater-equal, :version "1.8.0"}]]}]}' > $PWD/c-3.5.0.zip.dscard
if java -jar ../../target/uberjar/degasolv-1.0.2-SNAPSHOT-standalone.jar generate-repo-index -d $PWD -o $PWD/index.dsrepo
then
    exit 1
fi
java -jar ../../target/uberjar/degasolv-1.0.2-SNAPSHOT-standalone.jar generate-card -i "c" -v "3.5.0" -l "https://example.com/repo/c-3.5.0.zip" -r "e>=1.8.0" -o $PWD/c-3.5.0.zip.dscard
java -jar ../../target/uberjar/degasolv-1.0.2-SNAPSHOT-standalone.jar generate-repo-index -d $PWD -o $PWD/index.dsrepo
if java -jar ../../target/uberjar/degasolv-1.0.2-SNAPSHOT-standalone.jar resolve-locations -r $PWD/index.dsrepo "b"
then
    exit 1
fi
if java -jar ../../target/uberjar/degasolv-1.0.2-SNAPSHOT-standalone.jar query-repo -r $PWD/index.dsrepo --query "e>6.0.0"
then
    exit 1
fi
if java -jar ../../target/uberjar/degasolv-1.0.2-SNAPSHOT-standalone.jar --config-file test-data/repo/config.edn query-repo --query "!e"
then
    exit 1
fi
if java -jar ../../target/uberjar/degasolv-1.0.2-SNAPSHOT-standalone.jar --config-file test-data/repo/config.edn query-repo --query "!"
then
    exit 1
fi

java -jar ../../target/uberjar/degasolv-1.0.2-SNAPSHOT-standalone.jar generate-card -i "e" -v "1.8.0" -l "https://example.com/repo/e-1.8.0.zip" -o $PWD/e-1.8.0.zip.dscard
java -jar ../../target/uberjar/degasolv-1.0.2-SNAPSHOT-standalone.jar generate-repo-index -d $PWD -o $PWD/index.dsrepo
echo "These should succeed"
java -jar ../../target/uberjar/degasolv-1.0.2-SNAPSHOT-standalone.jar resolve-locations -r $PWD/index.dsrepo "b"
cat > $PWD/config.edn <<EOF
{  :repositories ["$PWD/index.dsrepo"]
}
EOF
java -jar ../../target/uberjar/degasolv-1.0.2-SNAPSHOT-standalone.jar --config-file $PWD/config.edn resolve-locations "b"
java -jar ../../target/uberjar/degasolv-1.0.2-SNAPSHOT-standalone.jar --config-file $PWD/config.edn query-repo --query "e>2.0.0"

java -jar ../../target/uberjar/degasolv-1.0.2-SNAPSHOT-standalone.jar --config-file $PWD/config.edn query-repo --query "e>2.0.0,!=2.1.0"
