#!/bin/sh
export POSIXLY_CORRECT=1
set -ex

rm -rf target

lein uberjar

name=$(lein print :name | sed 's|"||g')
version=$(lein print :version | sed 's|"||g')
desc=$(git describe --long --match '[0-9].[0-9].[0-9]')
previous_version=$(echo "${desc}" | sed 's|-.*$||g')
iteration=$(echo "${desc}" | sed -e 's|^[^-]*-||g' -e 's|-[^-]*$||g')
hash=$(git rev-parse HEAD)
builddate=$(date --utc '+%FT%H:%M%z')

mkdir -p pkg/
mkdir -p pkg/usr/bin/
mkdir -p pkg/usr/lib/${name}/
mkdir -p pkg/usr/share/doc/${name}/
cat > pkg/usr/share/doc/${name}/manifest.txt << MANIFEST
Name:               ${name}
Version:            ${version}
Previous Version:   ${previous_version}
Iteration:          ${iteration}
Git hash:           ${hash}
Build date:         ${builddate}
MANIFEST

cp target/uberjar/${name}-${version}-standalone.jar \
    pkg/usr/lib/degasolv/degasolv.jar

cp scripts/degasolv pkg/usr/bin

fpm \
    --verbose \
    --input-type dir \
    --output-type deb \
    --name "${name}" \
    --version "${version}" \
    --iteration "${iteration}.djh987" \
    --license "Eclipse Public License" \
    --architecture "all" \
    --depends "java-runtime" \
    --maintainer "djhaskin987@gmail.com" \
    --description "Dependency tracker with an eye toward building and shipping software." \
    --url "http://degasolv.readthedocs.io/en/latest/" \
    -C pkg

fpm \
    --verbose \
    --input-type dir \
    --output-type rpm \
    --name "${name}" \
    --version "${version}" \
    --iteration "${iteration}.djh987" \
    --license "Eclipse Public License" \
    --architecture "all" \
    --depends "java" \
    --maintainer "djhaskin987@gmail.com" \
    --description "Generic dependency resolver with an eye toward building software." \
    --url "http://degasolv.readthedocs.io/en/latest/" \
    -C pkg

mv *.deb target
mv *.rpm target
