#!/bin/sh
export POSIXLY_CORRECT=1
set -ex

name=degasolv
desc=$(git describe --long --match '[0-9].[0-9].[0-9]')
version=$(echo "${desc}" | sed 's|-.*$||g')
iteration=$(echo "${desc}" | sed -e 's|^[^-]*-||g' -e 's|-[^-]*$||g')
hash=$(git rev-parse HEAD)
builddate=$(date +%FT%H:%M%z --utc)

mkdir -p pkg/
mkdir -p pkg/usr/bin/
mkdir -p pkg/usr/lib/${name}/
mkdir -p pkg/usr/share/doc/${name}/
cat > pkg/usr/share/doc/${name}/manifest << MANIFEST
Name:       ${name}
Version:    ${version}-${iteration}
Git hash:   ${hash}
Build date: ${builddate}
MANIFEST





MANIFEST

cp target/uberjar/degasolv-${version}-standalone.jar pkg/usr/lib/degasolv/degasolv.jar

cp scripts/degasolv pkg/usr/bin

fpm \
    --verbose \
    --input-type dir \
    --output-type deb \
    --name "degasolv" \
    --version "${version}" \
    --iteration "${iteration}.djh987" \
    --license "Eclipse Public License" \
    --architecture "all" \
    --depends "java-runtime" \
    --maintainer "djhaskin987@gmail.com" \
    --description "Generic dependency resolver with an eye toward building software." \
    --url "http://degasolv.readthedocs.io/en/latest/" \
    -C pkg



