#!/bin/sh
export POSIXLY_CORRECT=1
set -x
if [ ! -f './project.clj' -a ! -f './build.boot' ]
then
    echo "This script must be run from the root of the project."
fi

test_home=test/resources/data/test-http-auth



name=$(lein print :name | sed 's|"||g')
version=$(lein print :version | sed 's|"||g')

java -jar test/resources/data/test-http-auth/wiremock-

java \
    -Xss16m \
    -jar target/uberjar/${name}-${version}-standalone.jar \
    query-repo \
    --repository "binary-amd64 file://${PWD}/${test_home}/avail /" \
    --package-system apt \
    --query "libc6"

try_time java \
lein run -- query-repo --repository http://abc:123@k70rg.mocklab.io/thing/8?fie=ongoodness --query d
