#!/bin/sh
set -eoux

export POSIXLY_CORRECT=1

if [ ! -f './project.clj' -a ! -f './build.boot' ]
then
    echo "This script must be run from the root of the project."
fi

root_path=${PWD}
test_home=test/resources/data/test-version-comparison

name=$(lein print :name | sed 's|"||g')
version=$(lein print :version | sed 's|"||g')

rm -rf "${test_home}"
mkdir -p "${test_home}"
cd "${test_home}"

ni=${root_path}/${name}-${version}-standalone
jar=${root_path}/target/uberjar/${name}-${version}-standalone.jar
runthis=
if [ -e "${ni}" ]
then
    runthis="${ni} -Xss16m"
else
    runthis="java -Xss16m -jar ${jar}"
fi

# First, generate *most* of the needed cards for the tests to pass.
${runthis} \
     generate-card \
     -i "a" \
     -v "1.0.0" \
     -l "https://example.com/repo/a-1.0.0.zip" \
     -C $PWD/a-1.0.0.zip.dscard

${runthis} \
     generate-card \
     -i "a" \
     -v "1.0.0-1" \
     -l "https://example.com/repo/a-1.0.0-1.zip" \
     -C $PWD/a-1.0.0-1.zip.dscard

${runthis} \
    generate-repo-index \
    -d $PWD \
    -I $PWD/index.dsrepo

output=$(${runthis} \
    resolve-locations \
    -R ${PWD}/index.dsrepo \
    -V maven \
    --requirement "a>1.0.0")

printf '%s\n' "${output}"

echo "${output}" | grep -qE '==1\.0\.0-1 @'

output=$(${runthis} \
    resolve-locations \
    -R ${PWD}/index.dsrepo \
    -V maven \
    --requirement "a<1.0.0-1")

printf '%s\n' "${output}"

echo "${output}" | grep -qE '==1\.0\.0 @'

output=$(${runthis} \
    resolve-locations \
    -R ${PWD}/index.dsrepo \
    -V semver \
    --requirement "a<1.0.0")

printf '%s\n' "${output}"

echo "${output}" | grep -qE '==1\.0\.0-1 @'

output=$(${runthis} \
    resolve-locations \
    -R ${PWD}/index.dsrepo \
    --requirement "a>1.0.0-1")

printf '%s\n' "${output}"

echo "${output}" | grep -qE '==1\.0\.0 @'
