#!/bin/sh
set -eoux

export POSIXLY_CORRECT=1

if [ ! -f './project.clj' -a ! -f './build.boot' ]
then
    echo "This script must be run from the root of the project."
fi

root_path=${PWD}
test_home=test/resources/data/test-search-strat

name=$(lein print :name | sed 's|"||g')
version=$(lein print :version | sed 's|"||g')

rm -rf "${test_home}"
mkdir -p "${test_home}"
cd "${test_home}"

# First, generate *most* of the needed cards for the tests to pass.

./${name}-${version}-standalone \
     generate-card \
     -i "a" \
     -v "1.0.0" \
     -l "https://example.com/repo/a-1.0.0.zip" \
     -r "b" \
     -r "c|d" \
     -C $PWD/a-1.0.0.zip.dscard

./${name}-${version}-standalone \
     generate-card \
     -i "b" \
     -v "1.0.0" \
     -l "https://example.com/repo/b-1.0.0.zip" \
     -r "d|c" \
     -C $PWD/b-1.0.0.zip.dscard

./${name}-${version}-standalone \
     generate-card \
     -i "c" \
     -v "1.0.0" \
     -l "https://example.com/repo/c-1.0.0.zip" \
     -C $PWD/c-1.0.0.zip.dscard

./${name}-${version}-standalone \
     generate-card \
     -i "d" \
     -v "1.0.0" \
     -l "https://example.com/repo/d-1.0.0.zip" \
     -C $PWD/d-1.0.0.zip.dscard

./${name}-${version}-standalone \
    generate-repo-index \
    -d $PWD \
    -I $PWD/index.dsrepo

# should fail
if ./${name}-${version}-standalone \
    resolve-locations \
    --search-strat deapth-first \
    -R ${PWD}/index.dsrepo \
    --requirement a
then
    exit 1
fi

./${name}-${version}-standalone \
    resolve-locations \
    --search-strat depth-first \
    -R ${PWD}/index.dsrepo \
    --requirement a

output1=$(./${name}-${version}-standalone \
    resolve-locations \
    -R ${PWD}/index.dsrepo \
    --requirement a)

printf '%s\n' "${output1}"

output2=$(./${name}-${version}-standalone \
    resolve-locations \
    --search-strat breadth-first \
    -R ${PWD}/index.dsrepo \
    --requirement a)

printf '%s\n' "${output2}"

if [ "${output1}" != "${output2}" ]
then
    exit 1
fi
