#!/bin/sh
export POSIXLY_CORRECT=1

if [ ! -f './project.clj' -a ! -f './build.boot' ]
then
    echo "This script must be run from the root of the project."
fi

test_home=test/resources/data/apt

name=$(lein print :name | sed 's|"||g')
version=$(lein print :version | sed 's|"||g')

time java -jar target/uberjar/${name}-${version}-standalone.jar resolve-locations --repository "binary-amd64 file://${PWD}/${test_home} /" --package-system apt --requirement "libc6"
time java -jar target/uberjar/${name}-${version}-standalone.jar resolve-locations --repository "binary-amd64 file://${PWD}/${test_home} /" --package-system apt --requirement "bash"
time java -jar \
    target/uberjar/${name}-${version}-standalone.jar \
    resolve-locations \
    --repository "binary-i386 file://${PWD}/${test_home}/i386 /" \
    --repository "binary-amd64 file://${PWD}/${test_home}/amd64 /" \
    --repository "binary-amd64 file://${PWD}/${test_home}/avail /" \
    --package-system apt \
    --resolve-strat fast \
    --requirement "ubuntu-desktop"
