#!/bin/sh

set -ex

root_path=${PWD}
test_home=test/resources/data/test-option-packs

rm -rf "${test_home}"
mkdir -p "${test_home}"

name=$(lein print :name | sed 's|"||g' )
version=$(lein print :version | sed 's|"||g')

cat > ${test_home}/test-option-packs.edn <<EDN
{
    :option-packs ["firstfound-version-mode"]
}
EDN

./${name}-${version}-standalone \
    -c ${test_home}/test-option-packs.edn \
    display-config | grep -E ':conflict-strat "prioritized"'


./${name}-${version}-standalone \
     -k "multi-version-mode" \
    display-config | grep -E ':conflict-strat "inclusive"'

./${name}-${version}-standalone \
     -c ${test_home}/test-option-packs.edn \
     -k "multi-version-mode" \
    display-config | grep -E ':conflict-strat "inclusive"'
