#!/bin/sh
set -ex

if [ ! -f './project.clj' -a ! -f './build.boot' ]
then
    echo "This script must be run from the root of the project."
fi
root_path=${PWD}
test_home=test/resources/data/test-subproc

name=$(lein print :name | sed 's|"||g')
version=$(lein print :version | sed 's|"||g')

ni=${root_path}/${name}-${version}-standalone
jar=${root_path}/target/uberjar/${name}-${version}-standalone.jar
runthis=
if [ -e "${ni}" ]
then
    runthis="${ni} -Xss16m"
else
    runthis="java -Xss16m -jar ${jar}"
fi

set +x
echo "Testing required argument..."
set -x

if ${runthis} resolve-locations -r quiles -R farforshire -t subproc
then
    exit 1
fi

set +x
echo "Testing argument validation..."
set -x

if ${runthis} resolve-locations -r quiles -x '/usr/bin/fightme' -R farforshire
then
    exit 1
fi

set +x
echo "Basic JSON test..."
set -x
${runthis} \
     resolve-locations \
     -x "test/resources/scripts/subproc" \
     -t subproc \
     -r "a>=2.0.0" \
     -R "thisdoesntmatter"


set +x
echo "Basic EDN test..."
set -x
${runthis} \
     resolve-locations \
     -t subproc \
     -r "a>=2.0.0" \
     -x "test/resources/scripts/subproc-edn" \
     -u "edn" \
     -R "thisdoesntmatter"

set +x
echo "Basic bad-exit test..."
set -x

if ${runthis} \
     resolve-locations \
     -t subproc \
     -r "a>=2.0.0" \
     -x "test/resources/scripts/bad-subproc" \
     -u "edn" \
     -R "thisdoesntmatter"
then
    exit 1
fi
