#!/bin/sh
set -eoux

export POSIXLY_CORRECT=1

if [ ! -f './project.clj' -a ! -f './build.boot' ]
then
    echo "This script must be run from the root of the project."
fi

root_path=${PWD}
test_home=test/resources/data/test-version-comparison

name=$(lein print :name | sed 's|"||g')
version=$(lein print :version | sed 's|"||g')

rm -rf "${test_home}"
mkdir -p "${test_home}"
cd "${test_home}"

# First, generate the needed cards for resolution.

java -jar ${root_path}/target/uberjar/${name}-${version}-standalone.jar \
     generate-card \
     -i "a" \
     -v "1.0.0" \
     -r "b" \
     -l "https://example.com/repo/a-1.0.0.zip" \
     -C $PWD/a-1.0.0.zip.dscard

java -jar ${root_path}/target/uberjar/${name}-${version}-standalone.jar \
    generate-card \
    -i "a" \
    -v "1.0.1" \
    -l "https://example.com/repo/a-1.0.1.zip" \
    -C $PWD/a-1.0.1.zip.dscard

java -jar ${root_path}/target/uberjar/${name}-${version}-standalone.jar \
     generate-repo-index \
     -d $PWD \
     -I $PWD/index.dsrepo

java -jar ${root_path}/target/uberjar/${name}-${version}-standalone.jar \
    query-repo \
    -R ${PWD}/index.dsrepo \
    --output-format json \
    --query "a"

if java -jar ${root_path}/target/uberjar/${name}-${version}-standalone.jar \
    query-repo \
    -R ${PWD}/index.dsrepo \
    --output-format json \
    --query "a>2.0"
then
    exit 1
fi

if ! java -jar ${root_path}/target/uberjar/${name}-${version}-standalone.jar \
    query-repo \
    -R ${PWD}/index.dsrepo \
    --enable-error-format \
    --output-format json \
    --query "a>2.0" | jq .problems >/dev/null 2>&1
then
    exit 1
fi

java -jar ${root_path}/target/uberjar/${name}-${version}-standalone.jar \
    query-repo \
    -R ${PWD}/index.dsrepo \
    --output-format edn \
    --query "a"

if java -jar ${root_path}/target/uberjar/${name}-${version}-standalone.jar \
    query-repo \
    -R ${PWD}/index.dsrepo \
    --output-format edn \
    --query "a>2.0"
then
    exit 1
fi


if ! java -jar ${root_path}/target/uberjar/${name}-${version}-standalone.jar \
    query-repo \
    -R ${PWD}/index.dsrepo \
    --output-format edn \
    --enable-error-format \
    --query "a>2.0" | grep -q ':problems'
then
    exit 1
fi

java -jar ${root_path}/target/uberjar/${name}-${version}-standalone.jar \
    query-repo \
    -R ${PWD}/index.dsrepo \
    --query "a"

if java -jar ${root_path}/target/uberjar/${name}-${version}-standalone.jar \
    query-repo \
    -R ${PWD}/index.dsrepo \
    --query "a>2.0"
then
    exit 1
fi
