#!/bin/sh
export POSIXLY_CORRECT=1
set -ex

name=$(lein print :name | sed 's|"||g')
version=$(lein print :version | sed 's|"||g')
branch=$(git branch | awk '/^[*] /{print $2}')
builddate=$(date --utc '+%Y%m%d%H%M%S')
git_desc=$(git describe --long --match '[0-9].[0-9].[0-9]')
previous_version=$(echo "${git_desc}" | sed 's|-.*$||g')
iteration="$(echo "${git_desc}" | sed -e 's|^[^-]*-||g' -e 's|-[^-]*$||g')"
hash=$(git rev-parse HEAD)
description=$(lein print :description)
url=$(lein print :url)
version=$(echo "${version}" | sed -e 's|-SNAPSHOT||g')

cat > target/manifest << MANIFEST
name=${name}
version=${version}
branch=${branch}
builddate=${builddate}
git_desc=${git_desc}
description=${description}
previous_version=${previous_version}
iteration=${iteration}
hash=${hash}
url=${url}
MANIFEST
