#!/bin/sh
export POSIXLY_CORRECT=1
set -ex

. target/manifest

native-image -H:+ReportUnsupportedElementsAtRuntime -jar target/uberjar/${name}-${version}-standalone.jar

mkdir -p target/graal
mv ./${name}-${version}-standalone target/graal
