#!/bin/sh
export POSIXLY_CORRECT=1
set -ex

type="${1}"
shift

. target/manifest

native-image --verbose --enable-url-protocols=http,https -H:+ReportUnsupportedElementsAtRuntime -jar target/uberjar/${name}-${version}-standalone.jar
#native-image --verbose -H:+ReportUnsupportedElementsAtRuntime -jar target/uberjar/${name}-${version}-standalone.jar

mkdir -p target/graal

mkdir -p pkg/
mkdir -p pkg/usr/bin/
mkdir -p pkg/usr/lib/${name}/
mkdir -p pkg/usr/share/doc/${name}/

cat > pkg/usr/share/doc/${name}/manifest.txt << MANIFEST
Name:               ${name}
Version:            ${basic_version}
Previous Version:   ${previous_version}
Iteration:          ${iteration}
Git hash:           ${hash}
Build date:         ${builddate}
MANIFEST

cp ./${name}-${version}-standalone target/graal
cp ./${name}-${version}-standalone pkg/usr/bin/${name}

#cp target/uberjar/${name}-${version}-standalone.jar \
#    pkg/usr/lib/degasolv/degasolv.jar

#cp scripts/degasolv pkg/usr/bin

fpm \
    --verbose \
    --input-type dir \
    --output-type ${type} \
    --name "${name}" \
    --version "${basic_version}" \
    --iteration "${iteration}.djh987" \
    --license "Eclipse Public License" \
    --architecture "all" \
    --depends "${dep}" \
    --maintainer "djhaskin987@gmail.com" \
    --description "${description}" \
    --url "${url}" \
    -C pkg \
    .

mkdir -p target/package
mv *.${type} target/package
