#!/bin/sh
export POSIXLY_CORRECT=1
set -ex

type="${1}"
shift

lein test2junit
ls target/test-results
ls target/test-results/html
lein uberjar
buildutils/generate-manifest

name=$(lein print :name | sed 's|"||g')
version=$(lein print :version | sed 's|"||g')
basic_version=$(echo "${version}" | sed -e 's|-.*$||g')
branch=$(git branch | awk '/^[*] /{print $2}')
builddate=$(date --utc '+%Y%m%d%H%M%S')
git_desc=$(git describe --long --match '[0-9].[0-9].[0-9]')
previous_version=$(echo "${git_desc}" | sed 's|-.*$||g')
iteration="$(echo "${git_desc}" | sed -e 's|^[^-]*-||g' -e 's|-[^-]*$||g')"
hash=$(git rev-parse HEAD)
description=$(lein print :description)
url=$(lein print :url)

cat > target/manifest << MANIFEST
name=${name}
version=${version}
basic_version=${basic_version}
branch=${branch}
builddate=${builddate}
git_desc=${git_desc}
description=${description}
previous_version=${previous_version}
iteration=${iteration}
hash=${hash}
url=${url}
MANIFEST

native-image -H:+ReportUnsupportedElementsAtRuntime -jar target/uberjar/${name}-${version}-standalone.jar

mkdir -p target/graal

mkdir -p pkg/
mkdir -p pkg/usr/bin/
mkdir -p pkg/usr/lib/${name}/
mkdir -p pkg/usr/share/doc/${name}/

cat > pkg/usr/share/doc/${name}/manifest.txt << MANIFEST
Name:               ${name}
Version:            ${basic_version}
Previous Version:   ${previous_version}
Iteration:          ${iteration}
Git hash:           ${hash}
Build date:         ${builddate}
MANIFEST

cp ./${name}-${version}-standalone target/graal
cp ./${name}-${version}-standalone pkg/usr/bin/${name}

#cp target/uberjar/${name}-${version}-standalone.jar \
#    pkg/usr/lib/degasolv/degasolv.jar

#cp scripts/degasolv pkg/usr/bin

fpm \
    --verbose \
    --input-type dir \
    --output-type ${type} \
    --name "${name}" \
    --version "${basic_version}" \
    --iteration "${iteration}.djh987" \
    --license "Eclipse Public License" \
    --architecture "all" \
    --depends "${dep}" \
    --maintainer "djhaskin987@gmail.com" \
    --description "${description}" \
    --url "${url}" \
    -C pkg \
    .

mkdir -p target/package
mv *.${type} target/package
