#!/bin/sh
export POSIXLY_CORRECT=1
set -exuo

. target/manifest

find /tmp
sudo apt-get update
sudo dpkg -i target/package/*.deb || :
sudo apt-get install -y -f
java -version
dpkg-query -l degasolv
dpkg-query -L degasolv
degasolv --help
