#!/bin/sh
export POSIXLY_CORRECT=1
set -exuo

. target/manifest

find /tmp
find .
sudo apt-get update
sudo apt install -y /tmp/workspace/target/package/*.deb
dpkg-query -l degasolv
dpkg-query -L degasolv
degasolv --help
