#!/bin/sh

export POSIXLY_CORRECT=1
set -e

# ***
# This script builds the "legacy" library, puts it into a zip file, and uploads
# it to the NAS.

# ***
# This part compiles the SO file.
rm -rf cmake
mkdir -p cmake
cd cmake
cmake ..
make

# ***
# This part makes the zip file.
# Files are placed in 'external' because
# In other builds, that's the folder where
# they'll be expected
cat > manifest.txt <<MANIFEST
Name: liblegacy
Version: 0.8.0
Git Hash: $(git rev-parse HEAD)
MANIFEST
rm -rf external
mkdir -p external/lib
mkdir -p external/pkg/legacy
mv manifest.txt external/pkg/legacy/
cp -af ../include external
mv liblegacy.so external/lib/liblegacy.so
zip \
    -r liblegacy-0.8.0.zip \
    external

# ***
# This represents the "Push to NAS" step
cp liblegacy-0.8.0.zip ../../nas

# ***
# Create the degasolv card
degasolv -c ../degasolv.edn generate-card --card-file liblegacy-0.8.0.zip.dscard
cp liblegacy-0.8.0.zip.dscard ../../nas

# ***
# Update repo index
cd ../../nas
degasolv generate-repo-index
